[build-system]
requires = [
    "scikit-build-core>=0.11",
    "pybind11==3.0.1"
]
build-backend = "scikit_build_core.build"

[project]
name = "PyCrSDK"
version = "0.1.0"
description = "Python wrapper for Sony Camera Remote SDK"
requires-python = ">=3.9,<3.14"

[tool.scikit-build]
wheel.packages = ["installer/PyCrSDK"]
build-dir = "build/{wheel_tag}"

[tool.cibuildwheel]
build = "cp39-win_amd64 cp310-win_amd64 cp311-win_amd64 cp312-win_amd64 cp313-win_amd64"
test-command = 'python -c "import PyCrSDK; print(PyCrSDK.CameraManager)"'
