name: Build Python wheels

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - "v*"

  pull_request:

permissions:
  contents: write

jobs:
  build-wheels:
    name: Build Windows wheels
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          submodules: false

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.2.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >-
            delvewheel repair -w {dest_dir} {wheel} --add-path "${{ github.workspace }}\installer\PyCrSDK"

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: PyCrSDK-windows-wheels
          path: wheelhouse/*.whl

      - name: Publish release assets
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: wheelhouse/*.whl
          generate_release_notes: true
